
[workspace]
resolver = "2"


members = [
    "lantern_extras",
    "lantern_create_index",
    "lantern_embeddings",
    "lantern_embeddings_core",
    "lantern_cli",
    "lantern_daemon",
]

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true

[profile.dev]
panic = "unwind"

