FROM rust:1.72.0

# 1. Copy the files in your machine to the Docker image
WORKDIR /app
COPY . .

# Remove lantern_extras from workspace
RUN rm -rf lantern_extras && sed -i -e 's/"lantern_extras",//' Cargo.toml

# Build your program for release
RUN cargo build --release --package lantern_cli

# Run the binary
ENTRYPOINT ["./target/release/lantern-cli"]
