[package]
name = "lantern_extras"
version = "0.0.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg13"]
pg11 = ["pgrx/pg11", "pgrx-tests/pg11" ]
pg12 = ["pgrx/pg12", "pgrx-tests/pg12" ]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13" ]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14" ]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15" ]
pg_test = []

[dependencies]
pgrx = "=0.9.7"
flate2 = "1.0"
ftp = "3"
tar = "0.4"
itertools = "0.11"
backtrace = "0.3"
url = "2.2"
lantern_embeddings_core = { path = "../lantern_embeddings_core" }

[dev-dependencies]
pgrx-tests = "=0.9.7"

