[package]
name = "lantern_cli"
version = "0.0.27"
edition = "2021"

[[bin]]
name = "lantern-cli"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
lantern_external_index = { path = "../lantern_external_index" }
lantern_embeddings = { path = "../lantern_embeddings" }
lantern_daemon = { path = "../lantern_daemon" }
lantern_logger = { path = "../lantern_logger" }
lantern_index_autotune = { path = "../lantern_index_autotune" }
