[package]
name = "lantern_cli"
version = "0.1.3"
edition = "2021"

[[bin]]
name = "lantern-cli"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.0", features = ["derive"] }
anyhow = "1.0.75"
postgres = "0.19.7"
rand = "0.8.5"
linfa-clustering = { version = "0.7.0", features = ["ndarray-linalg"] }
linfa = "0.7.0"
ndarray = { version = "0.15.6", features = ["rayon"] }
rayon = "1.8.1"
md5 = "0.7.0"
isahc = "1.7.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.111"
gcp_auth = "0.10.0"
tokio-postgres = "0.7.10"
futures = "0.3.28"
tokio = { version = "1.33.0", features = ["full"] }
lazy_static = "1.4.0"
itertools = "0.11.0"
csv = "1.3.0"
url = "2.2"
num_cpus = "1.15.0"
ort = { version = "1.16.0", features = ["load-dynamic", "cuda", "openvino"] }
tokenizers = { version = "0.15.2", features = ["default"] }
image = { version = "0.24.9", features = ["jpeg", "png", "webp" ]}
sysinfo = "0.29.11"
nvml-wrapper = "0.9.0"
strum = { version = "0.25", features = ["derive"] }
tiktoken-rs = "0.5.8"
regex = "1.10.3"
postgres-types = { version = "0.2.6", features = ["derive"] }
usearch = { git = "https://github.com/Ngalstyan4/usearch.git", branch="main-lantern" }
